### ISSUE TITLE
Since when do we skid tools Nell?

### ISSUE THREAD

**Issue by cyberterr0rist** [Nell1337/ip-geolocation#3]
why the fuck you changed the look and used the same api as my code aswell as the same json parsing..? Tf?

**Comment by Nell1337** [comment]
what?

**Comment by cyberterr0rist** [comment]
This was fucking 17 days ago and it looked like my code offly similar so yea

**Comment by Nell1337** [comment]
nice logic bro, no evidence, just accuse someone of skidding something you made

**Comment by cyberterr0rist** [comment]
bro stfu I thought krypton sent it to you, anyways I got phone locked and my number ain't working I'll be back in a week if you dmmed me something
